# Don't build any extra formats, HTML and JSON will
# always be built by default.
formats:
  - none

requirements_file: requirements.txt

build:
  image: latest

python:
  pip_install: true
  setup_py_install: false
  version: 3.6
