---
  # TODO: increase SQL packet size to my.ini
  # mysql --host=luna -u root -e "SET GLOBAL max_allowed_packet = 67108864;"

- hosts: all
  tasks:
    - name: Copy Python requirements
      copy:
        src: ../../requirements.txt
        dest: /tmp/imodel_requirements.txt

    - name: Install required Python packages.
      pip:
        executable: "{{pipexe}}"
        # executable: pip3
        requirements: /tmp/imodel_requirements.txt
      become: yes

- hosts: sqlhost
  tasks:
    - name: Set maximum SQL packet size.
      mysql_variables:
        login_user: root
        login_password: "{{sqlpasswd}}" # should ideally use vault
        variable: max_allowed_packet
        value: 67108864

    # - mysql_user:
    #     name: sabaody
    #     password: 12345
    #     priv: 'sabaody.*:ALL'
    #     state: present
