---
  # TODO: increase SQL packet size to my.ini
  # mysql --host=luna -u root -e "SET GLOBAL max_allowed_packet = 67108864;"

- hosts: all
  tasks:
    - name: Install required Python packages.
      pip:
        requirements: ~/imodel_requirements.txt

- hosts: sqlhost
    - name: Set maximum SQL packet size.
      mysql_variables:
        variable: max_allowed_packet
        value: 67108864

    # - mysql_user:
    #     name: sabaody
    #     password: 12345
    #     priv: 'sabaody.*:ALL'
    #     state: present
