---

# Setting up SupervisorD
#- hosts: all
  #tasks:
    #- name: Installing SupervisorD
      #pip:  name=supervisor version=3.3.4

    #- name: Creating Configuration File
      #shell: echo_supervisord_conf > ~/supervisord.conf

    #- name: Including Configuration
      #lineinfile: dest=~/supervisord.conf regexp='files = \~\/supervisord' line='\n[inet_http_server]\nport=*:9001\n\n[include]\nfiles = ~/supervisord.d/*.conf'


# Setting up Zookeeper
- hosts: kafka_zookeeper
  tasks:

    - name: Creating Directories
      file: path={{item}} state=directory mode=0755
      with_items:
        - ~/dl
        - ~/supervisord.d
        - ~/zookeeper
        - ~/data00/logs/zookeeper
        - ~/data00/zookeeper/
        - ~/data00/logs/zookeeper/

    # Travis is in Germany, use a German mirror
    - name: Downloading Zookeeper
      shell: wget -P ~/dl/ ftp://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.apache.org/dist/zookeeper/zookeeper-3.4.12/zookeeper-3.4.12.tar.gz

    - name: Extracting Zookeeper
      unarchive: src=~/dl/zookeeper-3.4.12.tar.gz dest=~/zookeeper/ mode=0755 remote_src=yes

    - name: Configuring Zookeeper
      template: src=../configs/zoo.cfg.j2 dest=~/zookeeper/zookeeper-3.4.12/conf/zoo.cfg mode=0755

    # https://stackoverflow.com/questions/30794025/ansible-how-can-i-set-serial-numbers-for-hosts
    - name: Set Zookeeper Id
      set_fact: zk_id={{item.0 + 1}}
      with_indexed_items: "{{groups['kafka_zookeeper']}}"
      when: item.1 == "{{inventory_hostname}}"

    - name: Copy SupervisorD Zookeeper Config File
      copy: src=../configs/zookeeper.conf dest=~/supervisord.d/ mode=0755


- hosts: kafka
  tasks:
    - name: Creating Directories
      file: path={{item}} state=directory mode=0755
      with_items:
        - ~/dl
        - ~/supervisord.d
        - ~/zookeeper
        - ~/data00/logs/zookeeper
        - ~/data00/zookeeper/
        - ~/data00/logs/zookeeper/
        - ~/kafka
        - ~/kafka/manager
        - ~/data00/kafka
        - ~/data01/kafka
        - ~/data00/logs/kafka

    # Travis is in Germany, use a German mirror
    - name: Downloading Kafka
      shell: wget -P ~/dl/ ftp://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.apache.org/dist/kafka/1.1.0/kafka_2.11-1.1.0.tgz

    - name: Extract Kafka
      unarchive: src=~/dl/kafka_2.11-1.1.0.tgz dest=~/kafka mode=0755 remote_src=yes

    - name: Write Kafka Server Configuration file
      template: src=../configs/server.properties.j2 dest=~/kafka/kafka_2.11-1.1.0/config/server.properties mode=0755

    - name: Write Consumer properties
      template: src=../configs/consumer.properties.j2 dest=~/kafka/kafka_2.11-1.1.0/config/consumer.properties mode=0755

    - name: Write Producer properties
      template: src=../configs/producer.properties.j2 dest=~/kafka/kafka_2.11-1.1.0/config/producer.properties mode=0755

    - name: Copy SupervisorD Kafka Config File
      copy: src=../configs/kafka.conf dest=~/supervisord.d/ mode=0755
