---

- hosts: all
  tasks:
    - name: Write environment variables for Apache tool paths
      template: src=../configs/imodel-paths.j2 dest=~/.imodel-paths


    - name: Add paths to .profile
      lineinfile:
        path: ~/.profile
        line: 'source ~/.imodel-paths'


    - name: Add .profile to .zshrc
      lineinfile:
        path: ~/.zshrc
        line: 'source ~/.profile'


    - name: Create config directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - ~/config
        - ~/config/hadoop
        - ~/config/spark
        - ~/config/kafka
        - ~/config/zookeeper
        - ~/config/elasticsearch


    - name: Create hadoop data directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - ~/data
        - ~/data/dataNode
        - ~/data/nameNode

    - name: Write hadoop config
      template: src=../configs/hadoop/core-site.xml.j2 dest=~/config/hadoop/core-site.xml
