---

- hosts: all
  tasks:
    - name: Write environment variables for Apache tool paths
      template: src=../configs/imodel-paths.j2 dest=~/.imodel-paths


    - name: Check if imodel-deps repo exists.
      stat:
        path: ~/imodel-deps
      register: imodel_deps_dir


    - name: Clone imodel-deps repository
      git:
        repo: https://github.com/0u812/imodel-deps.git
        version: master
        dest: ~/imodel-deps
      when: not imodel_deps_dir.stat.exists


    - name: Add paths to .profile
      lineinfile:
        path: ~/.profile
        line: 'source ~/.imodel-paths'


    - name: Add .profile to .zshrc
      lineinfile:
        path: ~/.zshrc
        line: 'source ~/.profile'


    - name: Create config directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - ~/config
        - ~/config/hadoop
        - ~/config/spark
        - ~/config/kafka
        - ~/config/zookeeper
        - ~/config/elasticsearch

    # Hadoop
    - name: Create hadoop data directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - ~/data
        - ~/data/dataNode
        - ~/data/nameNode

    - name: Get hadoop config files
      shell   : ls ~/imodel-deps/hadoop-2.7.7/etc/hadoop/*
      register: hadoop_config_files

    - name: Copy hadoop config files
      copy:
        remote_src: True
        src: "{{ item }}"
        dest: ~/config/hadoop
      with_items: "{{ hadoop_config_files.stdout_lines | reject('search', 'core-site.xml') | reject('search', 'hdfs-site.xml') | reject('search', 'slaves') | reject('search', 'hadoop-env.sh') | list }}"

    - name: Write hadoop config files
      template: src=../configs/hadoop/core-site.xml.j2 dest=~/config/hadoop/core-site.xml

    - name: Write hadoop config files
      template: src=../configs/hadoop/hdfs-site.xml.j2 dest=~/config/hadoop/hdfs-site.xml

    - name: Write hadoop config files
      template: src=../configs/hadoop/hadoop-env.sh.j2 dest=~/config/hadoop/hadoop-env.sh

    - name: Write hadoop config files
      template: src=../configs/hadoop/slaves.j2 dest=~/config/hadoop/slaves


    # Spark
    - name: Get spark config files
      shell   : ls ~/imodel-deps/spark-2.4.0-bin-hadoop2.7/conf/*
      register: spark_config_files

    - name: Copy spark config files
      copy:
        remote_src: True
        src: "{{ item }}"
        dest: ~/config/spark
      with_items: "{{ spark_config_files.stdout_lines | reject('search', 'spark-env.sh') | reject('search', '.template') | list }}"

    - name: Write spark config files
      template: src=../configs/spark/spark-env.sh.j2 dest=~/config/spark/spark-env.sh

    - name: Write spark config files
      template: src=../configs/hadoop/slaves.j2 dest=~/config/spark/slaves

    - name: Write spark config files
      template: src=../configs/spark/log4j.properties.j2 dest=~/config/spark/log4j.properties
